language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script:
  - flake8 android_clean_app.py test
  - nosetests
